### ISSUE TITLE
Invalid call to lazypipe().pipe(): argument is not a function.

### ISSUE THREAD

**Issue by bendavis78** [Collaborne/gulp-polymer-build-utils#5]
Using this code in `gulpfile.js`:

```
gulp.task('build', build);
function build() {
  return polymerBuildUtils.polymerBuild(polymerJson)
    .pipe(polymerBuildUtils.addCspCompliance())
    .pipe(polymerBuildUtils.addCacheBusting())
    .pipe(polymerBuildUtils.optimizeAssets())
    .pipe(polymerBuildUtils.injectCustomElementsEs5Adapter())
    .pipe(gulp.dest(buildDirectory));
}
```

Getting this error:

```
Error: Invalid call to lazypipe().pipe(): argument is not a function.
    Remember not to call stream creation functions directly! e.g.: pipe(foo), not pipe(foo())
    at validateStep (/home/ben/Projects/fnw-app/node_modules/lazypipe/index.js:11:10)
    at Function.build.pipe (/home/ben/Projects/fnw-app/node_modules/lazypipe/index.js:36:4)
    at Object.<anonymous> (/home/ben/Projects/fnw-app/inject-environment.js:25:4)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
```

**Comment by bendavis78** [comment]
Sorry, wasn't an issue with this plugin.
